# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Blog"
description: > # this means to ignore newlines until "email:"
   The place where I write about the boring stuff I do.

email: pinak.ahuja@gmail.com
#blog logo
logo: "/assets/images/logo.png"
# blog cover
cover: "/assets/images/background.jpg"

name: 'Pinak Ahuja'
author: 'Pinak Ahuja'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://blog.pinak.me" # the base hostname & protocol for your site
baseurl: ""

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/PinakAhuja
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/pinak.ahuja
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/pinak
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
